name: Playwright Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: playwright
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4

      - name: dependancy install
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: playwright
        run: npm test

